<script src="/javascripts/prototype.js" type="text/javascript"></script>
<script src="/javascripts/scriptaculous/scriptaculous.js" type="text/javascript"></script>
<script src="/javascripts/swui/swui_third-party.js" type="text/javascript"></script>
<script src="/javascripts/swui/swui_rhet.js" type="text/javascript"></script>
<script src="/javascripts/swui/swui_model.js" type="text/javascript"></script>
<script src="/javascripts/swui/swui_common.js" type="text/javascript"></script>
<script src="/javascripts/swui/swui_dom.js" type="text/javascript"></script>

