#!/usr/bin/env ruby

#jruby -S script/import path/para/o/arquivo.rdf model=nomedabase format=rdfxml

require File.expand_path('../../config/boot',  __FILE__)

Rails::Initializer.run do |config|
  config.frameworks -= [ :active_record , :active_resource, :action_mailer ]
  config.time_zone = 'UTC'
end

require 'active_rdf'

args = ARGV.map{|arg| arg.split("=")}
file = args.delete_at(0)
options = HashWithIndifferentAccess.new
for arg in args do
  options[arg.first] = arg.last
end

model  = options[:model]
format = options[:format].nil? ? :rdfxml : options[:format].to_sym
app    = Application.find(model)

app.start

app.db.load("file:#{file}", :format => format, :into => :default_model)
